---
- name: start Rally
  docker:
    name: ovn-rally
    image: "{{ rally_image_full }}"
    pull: "{{ image_pull_policy }}"
    privileged: yes
    detach: True
    state: started
    volumes:
      - "{{ node_config_directory }}/rally:/root/rally-ovn/"
      - "{{ node_config_directory }}/rally/ssh:/root/.ssh/"
