---
sudo: required
dist: trusty

env:
  - global:
    - DOCKER_VERSION=1.11.2-0~trusty

before_install:
    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

services:
  - docker

script: cd ci && INSTALLDOCKER=False OVNSUDO=sudo ./docker-rally.sh
