---
- name: Ensuring config directories exist on database
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "openvswitch-ovn-db"
  when:
    - inventory_hostname in groups['ovn-control']

- name: Copying over config.json files for OVN database
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "openvswitch-ovn-db"
  when:
    - inventory_hostname in groups['ovn-control']

- name: Ensuring config directories exist on chassis host
  file:
    path: "{{ node_config_directory }}/openvswitch-ovn-chassis-{{ item.1 }}"
    state: "directory"
    recurse: yes
  delegate_to: "{{ groups['emulation-hosts'][ item.0 ] }}"
  with_together:
        - "{{ dmi_data['ip_index'] }}"
        - "{{ dmi_data['ip_index_list'] }}"
  when:
    - inventory_hostname in groups['emulation-hosts']

- name: Copying over config.json files for services on chassis host
  template:
    src: "openvswitch-ovn-chassis.json.j2"
    dest: "{{ node_config_directory }}/openvswitch-ovn-chassis-{{ item.1 }}/config.json"
  delegate_to: "{{ groups['emulation-hosts'][ item.0 ] }}"
  with_together:
        - "{{ dmi_data['ip_index'] }}"
        - "{{ dmi_data['ip_index_list'] }}"
  when:
    - inventory_hostname in groups['emulation-hosts']

- name: Create user "{{ deploy_user }}" on all hosts
  user:
    name: "{{ deploy_user }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
  when: deploy_user != 'root'

- name: Copy authorized keys to user
  command: "cp -f /root/.ssh/authorized_keys /home/{{ deploy_user }}/.ssh/"
  when: deploy_user != 'root'

- name: Change ownership for authorized keys
  file:
    path: "/home/{{ deploy_user }}/.ssh"
    state: "directory"
    recurse: yes
    owner: "{{ deploy_user }}"
  when: deploy_user != 'root'
