---
- hosts:
    - ovn-control
    - emulation-hosts
  roles:
    - common
    - ovn

- hosts:
    - rally
  roles:
    - { role: common }
    - { role: rally,
        when: enable_rally_ovs | bool }
